-- Recover bundled-archive products into outfit_products.
-- Only inserts for outfits that:
--   1. Exist in the outfits table for the archive owner
--   2. Don't already have any products
-- Safe to re-run; idempotent due to NOT EXISTS guard.

INSERT INTO public.outfit_products (outfit_id, name, price, image, shop_link)
SELECT v.outfit_id, v.name, v.price, v.image, v.shop_link
FROM (VALUES
  ('outfit-1', 'INSULATED SHELL JACKET', '490 EUR', '/products/tnf-jacket.webp', NULL),
  ('outfit-1', 'WIDE LEG PANTS', '230 EUR', '/products/wide-leg-pants.webp', NULL),
  ('outfit-1', 'Waterproof Platform Boots', '', '/products/platform-boots.webp', NULL),
  ('outfit-2', 'INSULATED SHELL JACKET', '850 EUR', '/products/tnf-jacket.webp', NULL),
  ('outfit-2', 'WATERPROOF PLATFORM BOOTS', '420 EUR', '/products/platform-boots.webp', NULL),
  ('outfit-2', 'Patagonia Duffel Bag', '', '/products/patagonia-duffel-bag.webp', NULL),
  ('outfit-3', 'RELAXED STRAIGHT JEANS', '340 EUR', '/products/relaxed-straight-jeans.webp', NULL),
  ('outfit-3', 'ANKLE BOOTS', '210 EUR', '/products/ankle-boots.webp', NULL),
  ('outfit-4', 'COLLARLESS LEATHER JACKET', '550 EUR', '/products/collarless-leather-jacket.webp', NULL),
  ('outfit-4', 'WIDE LEG PANTS', '230 EUR', '/products/wide-leg-pants.webp', NULL),
  ('outfit-4', 'Waterproof Platform Boots', '', '/products/platform-boots.webp', NULL),
  ('outfit-5', 'Oversized Jean Shirt', '', '/products/oversized-jean-shirt.webp', NULL),
  ('outfit-5', 'Blue Striped Poplin Shirt', '', '/products/blue-striped-poplin-shirt.webp', NULL),
  ('outfit-5', 'High Rise Wide Legged Jeans', '', '/products/high-rise-wide-legged-jeans.webp', NULL),
  ('outfit-5', 'Ankle Boots', '', '/products/ankle-boots.webp', NULL),
  ('outfit-6', 'Black Evening Dress', '', '/products/black-evening-dress.webp', NULL),
  ('outfit-7', 'Shearling Jacket', '', '/products/shearling-jacket.webp', NULL),
  ('outfit-7', 'Waterproof Platform Boots', '420 EUR', '/products/platform-boots.webp', NULL),
  ('outfit-7', 'High Rise Flared Jeans', '', '/products/high-rise-flared-jeans.webp', NULL),
  ('outfit-8', 'TAILORED BROWN PANTS', '', '/products/tailored-brown-pants.webp', NULL),
  ('outfit-8', 'WHITE TURTLENECK', '', '/products/white-turtleneck.webp', NULL),
  ('outfit-8', 'Ankle Boots', '', '/products/ankle-boots.webp', NULL),
  ('outfit-9', 'Mini Checkered Skirt', '', '/products/mini-checkered-skirt.webp', NULL),
  ('outfit-9', 'Navy Wool Turtleneck', '', '/products/navy-wool-turtleneck.webp', NULL),
  ('outfit-10', 'Brown Wool Turtleneck', '', '/products/brown-wool-turtleneck.webp', NULL),
  ('outfit-10', 'Distressed Leather Mini Skirt', '', '/products/distressed-leather-mini-skirt.webp', NULL),
  ('outfit-10', 'Rubber Bridge Boots', '', '/products/rubber-bridge-boots.webp', NULL),
  ('outfit-11', 'High Rise Wide Legged Jeans', '', '/products/high-rise-wide-legged-jeans.webp', NULL),
  ('outfit-11', 'Navy Cardigan', '', '/products/navy-cardigan.webp', NULL),
  ('outfit-11', 'Mary Janes', '', '/products/mary-janes.webp', NULL),
  ('outfit-12', 'Mary Janes', '', '/products/mary-janes.webp', NULL),
  ('outfit-12', 'Tweed Mini Skirt', '', '/products/tweed-mini-skirt.webp', NULL),
  ('outfit-12', 'Cropped Tweed Jacket', '', '/products/cropped-tweed-jacket.webp', NULL),
  ('outfit-15', 'Vintage Shearling Jacket', '', '/products/vintage-shearling-jacket.webp', NULL),
  ('outfit-15', 'Black Boots', '', '/products/black-boots.webp', NULL),
  ('outfit-15', 'Distressed Leather Mini Skirt', '', '/products/distressed-leather-mini-skirt.webp', NULL),
  ('outfit-17', 'Rubber Bridge Boots', '', '/products/rubber-bridge-boots.webp', NULL),
  ('outfit-17', 'Navy Wool Turtleneck', '', '/products/navy-wool-turtleneck.webp', NULL),
  ('outfit-17', 'Jeans Mini Skirt', '', '/products/jeans-mini-skirt.webp', NULL),
  ('outfit-17', 'Beige Trenchcoat', '', '/products/beige-trenchcoat.webp', NULL),
  ('outfit-18', 'Vintage Jean Paul Gaultier Slip Dress', '', '/products/vintage-jpg-slip-dress.webp', NULL),
  ('outfit-20', 'Relaxed Straight Jeans', '', '/products/relaxed-straight-jeans.webp', NULL),
  ('outfit-20', 'White Cardigan', '', '/products/white-cardigan.webp', NULL),
  ('outfit-20', 'Mary Janes', '', '/products/mary-janes.webp', NULL),
  ('outfit-21', 'Ankle Boots', '', '/products/ankle-boots.webp', NULL),
  ('outfit-21', 'Navy Wool Vest', '', '/products/navy-wool-vest.webp', NULL),
  ('outfit-21', 'High Rise Bootcut Jeans', '', '/products/high-rise-bootcut-jeans.webp', NULL),
  ('outfit-25', 'Patterned Ski Jacket', '', '/products/patterned-ski-jacket.webp', NULL),
  ('outfit-25', 'Patterned Ski Pants', '', '/products/patterned-ski-pants.webp', NULL),
  ('outfit-25', 'Black Crows Skis', '', '/products/black-crows-skis.webp', NULL),
  ('outfit-26', 'Patterned Ski Jacket', '', '/products/patterned-ski-jacket.webp', NULL),
  ('outfit-26', 'Black Crows Skis', '', '/products/black-crows-skis.webp', NULL),
  ('outfit-26', 'North Face Ski Pants', '', '/products/north-face-ski-pants.webp', NULL),
  ('outfit-90', 'Ankle Boots', '', '/products/ankle-boots.webp', NULL),
  ('outfit-90', 'Black Tailored Trousers', '', '/products/black-tailored-trousers.webp', NULL),
  ('outfit-90', 'Black Tailored Coat', '', '/products/black-tailored-coat.webp', NULL),
  ('outfit-90', 'Bucket Hat', '', '/products/bucket-hat.webp', NULL),
  ('outfit-91', 'Sleeveless Knit', '', '/products/sleeveless-knit.webp', NULL),
  ('outfit-91', 'Balloon Sleeves Shirt', '', '/products/balloon-sleeves-shirt.webp', NULL),
  ('outfit-91', 'High Rise Wide Legged Jeans', '', '/products/high-rise-wide-legged-jeans.webp', NULL),
  ('outfit-92', 'Relaxed Straight Jeans', '', '/products/relaxed-straight-jeans.webp', NULL),
  ('outfit-92', 'Vintage 90''s Shirt', '', '/products/vintage-90s-shirt.webp', NULL),
  ('outfit-92', 'Vintage Trench Coat', '', '/products/vintage-trench-coat.webp', NULL),
  ('outfit-92', 'Black Loafers', '', '/products/black-loafers.webp', NULL),
  ('outfit-92', 'White Knit Sweater', '', '/products/white-knit-sweater.webp', NULL),
  ('outfit-93', 'Wide Legged Jeans', '', '/products/wide-legged-jeans.webp', NULL),
  ('outfit-93', 'Striped Sweater', '', '/products/striped-sweater.webp', NULL),
  ('outfit-94', 'Ankle Boots', '', '/products/ankle-boots.webp', NULL),
  ('outfit-94', 'Low Rise Straight Jeans', '', '/products/low-rise-straight-jeans.webp', NULL),
  ('outfit-94', 'Black Shoulder Pad Sweater', '', '/products/black-shoulder-pad-sweater.webp', NULL),
  ('outfit-95', 'Ankle Boots', '', '/products/ankle-boots.webp', NULL),
  ('outfit-95', 'Wide Legged Jeans', '', '/products/wide-legged-jeans.webp', NULL),
  ('outfit-95', 'White Shoulder Pad Knit', '', '/products/white-shoulder-pad-knit.webp', NULL),
  ('outfit-96', 'Ankle Boots', '', '/products/ankle-boots.webp', NULL),
  ('outfit-96', 'Check Suit Trousers', '', '/products/check-suit-trousers.webp', NULL),
  ('outfit-96', 'Brown Turtleneck', '', '/products/brown-turtleneck.webp', NULL),
  ('outfit-97', 'Brown Suede Coat', '', '/products/brown-suede-coat.webp', NULL),
  ('outfit-97', 'Brown Sweater Dress', '', '/products/brown-sweater-dress.webp', NULL),
  ('outfit-97', 'Black Heel Boots', '', '/products/black-heel-boots.webp', NULL),
  ('outfit-98', 'Low Rise Straight Jeans', '', '/products/low-rise-straight-jeans.webp', NULL),
  ('outfit-99', 'Wide Leg Pants', '', '/products/wide-leg-pants.webp', NULL),
  ('outfit-99', 'Waterproof Platform Boots', '', '/products/platform-boots.webp', NULL),
  ('outfit-99', 'White Turtleneck', '', '/products/white-turtleneck.webp', NULL),
  ('outfit-99', 'INSULATED SHELL JACKET', '', '/products/tnf-jacket.webp', NULL),
  ('outfit-100', 'Studded Heels', '', '/products/studded-heels.webp', NULL),
  ('outfit-100', 'Corset Dress', '', '/products/corset-dress.webp', NULL),
  ('outfit-101', 'Studded Heels', '', '/products/studded-heels.webp', NULL),
  ('outfit-101', 'Corset Dress', '', '/products/corset-dress.webp', NULL),
  ('outfit-102', 'Mary Janes', '', '/products/mary-janes.webp', NULL),
  ('outfit-102', 'Relaxed Straight Jeans', '', '/products/relaxed-straight-jeans.webp', NULL),
  ('outfit-102', 'Cropped Jacket', '', '/products/cropped-jacket.webp', NULL),
  ('outfit-103', 'Wide Leg Pants', '', '/products/wide-leg-pants.webp', NULL),
  ('outfit-103', 'Flint Knitted Sweater', '', '/products/flint-knitted-sweater.webp', NULL),
  ('outfit-103', 'Waterproof Platform Boots', '', '/products/platform-boots.webp', NULL),
  ('outfit-104', 'Black Leggings', '', '/products/black-leggings.webp', NULL),
  ('outfit-104', 'Adidas Sneakers', '', '/products/adidas-sneakers.webp', NULL),
  ('outfit-105', 'Ankle Boots', '', '/products/ankle-boots.webp', NULL),
  ('outfit-105', 'Low Rise Straight Jeans', '', '/products/low-rise-straight-jeans.webp', NULL),
  ('outfit-105', 'Carnot Coat', '', '/products/carnot-coat.webp', NULL),
  ('outfit-107', 'Rubber Bridge Boots', '', '/products/rubber-bridge-boots.webp', NULL),
  ('outfit-107', 'Kasia Dress', '', '/products/kasia-dress.webp', NULL),
  ('outfit-108', 'Rubber Bridge Boots', '', '/products/rubber-bridge-boots.webp', NULL),
  ('outfit-108', 'Kasia Dress', '', '/products/kasia-dress.webp', NULL),
  ('outfit-109', 'Oversized Black Fleece', '', '/products/oversized-black-fleece.webp', NULL),
  ('outfit-109', 'Black Leggings', '', '/products/black-leggings.webp', NULL),
  ('outfit-109', 'Adidas Sneakers', '', '/products/adidas-sneakers.webp', NULL),
  ('outfit-110', 'Gore-Tex Ski Jacket', '', '/products/goretex-ski-jacket.webp', NULL),
  ('outfit-110', 'Black Crows Skis', '', '/products/black-crows-skis.webp', NULL),
  ('outfit-110', 'North Face Ski Pants', '', '/products/north-face-ski-pants.webp', NULL),
  ('outfit-111', 'Rubber Bridge Boots', '', '/products/rubber-bridge-boots.webp', NULL),
  ('outfit-111', 'Mini Black Skirt', '', '/products/mini-black-skirt.webp', NULL),
  ('outfit-111', 'Mini Black Jacket', '', '/products/mini-black-jacket.webp', NULL)
) AS v(outfit_id, name, price, image, shop_link)
WHERE EXISTS (
  SELECT 1 FROM public.outfits o
  WHERE o.id = v.outfit_id AND o.user_id = '31c9f3fd-e672-43f2-954a-0b141640e76f'
)
AND NOT EXISTS (
  SELECT 1 FROM public.outfit_products op WHERE op.outfit_id = v.outfit_id
);

NOTIFY pgrst, 'reload schema';
